# .github/workflows/pre-commit.yml
name: Pre-Commit
on: push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: x64
      - run: pip install nox==2022.11.21
      - run: pip install poetry==1.3.2
      - run: pip install nox-poetry==1.0.2
      - run: nox --sessions pre-commit
