# .github/workflows/pypi.yml
name: Build package using poetry and publish on pypi
on:
  push:
    tags:
      - "*"
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: x64
      - run: pip install poetry==1.1.12
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          print_hash: true
          skip_existing: true
